# lab1

 this is my first lab.

In [3]:
import pandas as pd

covid_data = pd.read_csv( "s3://ia-340-crockett-bucketone561/data.csv" )
covid_data.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [4]:
data_gov = pd.read_csv( "s3://ia-340-crockett-bucketone561/Baton_Rouge_Police_Crime_Incidents.csv" )
data_gov.head()

/tmp/ipykernel_11095/494560279.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  data_gov = pd.read_csv( "s3://ia-340-crockett-bucketone561/Baton_Rouge_Police_Crime_Incidents.csv" )

,INCIDENT NUMBER,CHARGE ID,CHARGE DATE,REPORT DATE,APPROVED DATE,ATTEMPTED OR COMMITTED,STREET ADDRESS,SUBADDRESS,CITY,STATE,...,CRIME AGAINST,NIBRS CODE,NIBRS DESCRIPTION,CENSUS BLOCK GROUP,COUNCIL DISTRICT,CRIME PREVENTION DISTRICT,NEIGHBORHOOD,LONGITUDE,LATITUDE,GEOLOCATION
0,19-082654,AFF2B61F-AC22-46D5-982D-3CA140D57369,09/08/2019 03:08:00 AM,07/14/2021 01:51:06 PM,07/29/2021 09:00:41 AM,COMMITTED,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20-015556,8929E25E-778E-44C0-9387-70ADBD1F02C1,02/18/2020 02:28:00 PM,02/10/2021 10:05:30 AM,02/10/2021 02:25:17 PM,COMMITTED,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25-152907,2797533,05/28/2025 04:10:00 AM,05/28/2025 04:10:25 AM,06/20/2025 03:00:37 AM,COMPLETED,11296 GOODWOOD BLVD,NaN,BATON ROUGE,LA,...,SOCIETY,35B,DRUG EQUIPMENT VIOLATIONS,NaN,6.0,SHERWOOD FOREST,SHERWOOD FOREST,-91.05828,30.44837,POINT (-91.058281 30.448374)
3,25-500467,2798913,04/21/2025 12:00:00 AM,06/19/2025 09:28:00 AM,06/19/2025 02:19:10 PM,COMPLETED,9705 FLORIDA BLVD,NaN,BATON ROUGE,LA,...,PROPERTY,26A,FALSE PRETENSES/SWINDLE/CONFIDENCE GAME,NaN,6.0,NaN,CORTANA / VILLA DEL REY,-91.07835,30.45616,POINT (-91.078353 30.456164)
4,25-158798,2794602,06/12/2025 11:10:00 AM,06/12/2025 11:10:02 AM,06/18/2025 08:41:02 AM,COMPLETED,3430 OSWEGO ST,NaN,BATON ROUGE,LA,...,PROPERTY,290,DESTRUCTION/DAMAGE/VANDALISM OF PROPERTY,NaN,7.0,NaN,NORTH BATON ROUGE,-91.15530,30.48038,POINT (-91.155296 30.480378)